# Generated by Django 2.2.15 on 2020-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_auto_20200904_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
