# Generated by Django 2.2.15 on 2020-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_auto_20200905_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
