# Generated by Django 2.2.15 on 2020-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_auto_20200911_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
