# Generated by Django 2.2.15 on 2020-09-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
