# Generated by Django 2.2.15 on 2020-09-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_auto_20200912_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchaseorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.PurchaseOrder'),
        ),
    ]
