# Generated by Django 2.2.15 on 2020-09-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0009_purchaseorderitem_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='outstanding_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
