# Generated by Django 2.2.15 on 2020-09-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0010_purchaseorderitem_outstanding_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='items_received',
            field=models.BooleanField(default=False),
        ),
    ]
