# Generated by Django 2.2.15 on 2020-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0011_purchaseorderitem_items_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['items_received', 'pk']},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PART_RECEIPT', 'Part Receipt'), ('COMPLETE', 'Complete')], max_length=200),
        ),
    ]
