# Generated by Django 2.2.15 on 2020-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0012_auto_20200915_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
