# Generated by Django 2.2.15 on 2020-09-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0013_auto_20200916_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_status',
            new_name='status',
        ),
    ]
