# Generated by Django 2.2.15 on 2020-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0014_auto_20200916_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['items_received', 'received_qty', 'pk']},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Part Receipt', 'Part Receipt'), ('Complete', 'Complete')], max_length=200),
        ),
    ]
