# Generated by Django 2.2.15 on 2020-09-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0015_auto_20200917_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_batch_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
