# Generated by Django 2.2.15 on 2020-09-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0016_purchaseorderitem_received_batch_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='received_batch_qty',
            new_name='delivery_qty',
        ),
    ]
