# Generated by Django 2.2.15 on 2020-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0018_purchaseorderitem_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
