# Generated by Django 2.2.15 on 2020-09-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0019_purchaseorderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='date_updated2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
