# Generated by Django 2.2.15 on 2020-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0020_purchaseorderitem_date_updated2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='date_added',
        ),
    ]
