# Generated by Django 2.2.15 on 2020-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0022_remove_purchaseorderitem_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='date_updated2',
            new_name='date_updated',
        ),
    ]
