# Generated by Django 2.2.15 on 2020-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0023_auto_20200919_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['items_received', 'received_qty', 'date_updated', 'pk']},
        ),
    ]
