# Generated by Django 2.2.15 on 2020-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0025_auto_20200921_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Reveived', 'Received')], default='Pending', max_length=200),
        ),
    ]
