# Generated by Django 2.2.15 on 2020-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0026_purchaseorderitem_received_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('1 - Pending', 'Pending'), ('2 - Partially Received', 'Partial'), ('3 - All Reveived', 'Received')], default='Pending', max_length=200),
        ),
    ]
