# Generated by Django 2.2.15 on 2020-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0027_auto_20200921_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['received_status', 'product__sku']},
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('1-Pending', 'Pending'), ('2-Partially Received', 'Partial'), ('3-All Reveived', 'Received')], default='Pending', max_length=200),
        ),
    ]
