# Generated by Django 2.2.15 on 2020-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0030_auto_20200921_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('Pending', '1-Pending'), ('Partial', '2-Partially Received'), ('Received', '3-All Reveived')], default='1-Pending', max_length=200),
        ),
    ]
