# Generated by Django 2.2.15 on 2020-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0031_auto_20200921_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='items_received',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('Order Pending', 'Received All Items'), ('Partially Received', 'Partially Items'), ('Received All Items', 'Received All Items')], default='1-Pending', max_length=200),
        ),
    ]
