# Generated by Django 2.2.15 on 2020-09-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0034_auto_20200921_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_status',
            field=models.CharField(blank=True, choices=[('Order Pending', 'Order Pending'), ('Partially Received', 'Partially Items'), ('All Items Received', 'All Items Received')], default='Order Pending', max_length=200),
        ),
    ]
