# Generated by Django 2.2.15 on 2020-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0037_purchaseorderitem_status_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['status_ordering', 'product__sku']},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
