# Generated by Django 2.2.15 on 2020-09-21 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0039_purchaseorder_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date_added2',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
