# Generated by Django 2.2.15 on 2020-09-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0040_purchaseorder_date_added2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='date_added',
        ),
    ]
