# Generated by Django 2.2.15 on 2020-09-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0042_auto_20200921_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-pk']},
        ),
    ]
