# Generated by Django 2.2.15 on 2020-09-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0045_auto_20200923_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['status_ordering', 'id']},
        ),
    ]
