# Generated by Django 2.2.15 on 2020-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0047_auto_20201001_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='label',
            field=models.BooleanField(default=False),
        ),
    ]
