# Generated by Django 2.2.15 on 2020-10-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0050_purchaseorderitem_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['-date_updated', '-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='img/no-image.png', null=True, upload_to='img/products'),
        ),
    ]
