# Generated by Django 2.2.15 on 2020-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0052_auto_20201011_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='img/no-image.png', null=True, upload_to='img/products'),
        ),
    ]
