# Generated by Django 2.2.15 on 2020-10-13 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0056_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='delivery_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('Online Sale', 'Online Sale'), ('Stock Receipt', 'Stock Receipt'), ('Manual Adjustment', 'Manual Adjustment')], max_length=200, null=True),
        ),
    ]
