# Generated by Django 2.2.15 on 2020-10-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0057_auto_20201013_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('Online Sale', 'Online Sale'), ('Purchase Order Receipt', 'Purchase Order Receipt'), ('Manual Adjustment', 'Manual Adjustment')], max_length=200, null=True),
        ),
    ]
