# Generated by Django 2.2.15 on 2020-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0059_stockmovement_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='stock_movement_added',
            field=models.BooleanField(default=False),
        ),
    ]
