# Generated by Django 2.2.15 on 2020-10-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0060_purchaseorderitem_stock_movement_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='delivery_qty',
            new_name='stock_qty',
        ),
    ]
