# Generated by Django 2.2.15 on 2020-10-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0013_orderitem_stock_movement_added'),
        ('app_products', '0061_auto_20201013_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order'),
        ),
    ]
