# Generated by Django 2.2.15 on 2020-10-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0062_stockmovement_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='stock_qty',
            new_name='adjustment_qty',
        ),
    ]
