# Generated by Django 2.2.15 on 2020-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0063_auto_20201014_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
