# Generated by Django 2.2.15 on 2020-10-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0064_auto_20201014_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='stock_movement_added',
        ),
    ]
