# Generated by Django 2.2.15 on 2020-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0065_remove_purchaseorderitem_stock_movement_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='current_stock_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
