# Generated by Django 2.2.15 on 2020-10-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0068_product_orizaba_init_stock_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orizaba_init_stock_qty',
            new_name='orizaba_initial_stock_qty',
        ),
    ]
