# Generated by Django 2.2.15 on 2020-10-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0069_auto_20201014_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orizaba_initial_stock_qty',
        ),
    ]
