# Generated by Django 2.2.15 on 2020-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0071_auto_20201015_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
