# Generated by Django 2.2.15 on 2020-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0073_auto_20201015_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
