# Generated by Django 2.2.15 on 2020-10-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0014_auto_20201015_2144'),
        ('app_products', '0075_auto_20201015_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='orderitem_id',
            field=models.ForeignKey(blank=True, db_column='orderitem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderItem', unique=True),
        ),
    ]
