# Generated by Django 2.2.15 on 2020-10-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0077_auto_20201015_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='orderitem_id',
        ),
    ]
