# Generated by Django 2.2.15 on 2020-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0078_remove_stockmovement_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
