# Generated by Django 2.2.15 on 2020-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0080_auto_20201016_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_discrepancy',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
