# Generated by Django 2.2.15 on 2020-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0081_product_stock_discrepancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_balances',
            field=models.BooleanField(default=True),
        ),
    ]
