# Generated by Django 2.2.15 on 2020-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0082_product_stock_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unleashed_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Unleashed Updated', 'Unleashed Updated')], default='Pending', max_length=200, null=True),
        ),
    ]
