# Generated by Django 2.2.15 on 2020-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0083_stockmovement_unleashed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
