# Generated by Django 2.2.15 on 2020-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0085_stockmovement_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
