# Generated by Django 2.2.15 on 2020-11-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0086_auto_20201021_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date_added', '-pk']},
        ),
    ]
