# Generated by Django 2.2.15 on 2021-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0087_auto_20201105_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
