# Generated by Django 2.2.15 on 2021-01-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0089_purchaseorderitem_date_updated_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='date_updated_2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
