# Generated by Django 2.2.15 on 2021-01-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0090_auto_20210113_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='date_updated_2',
        ),
    ]
