# Generated by Django 2.2.15 on 2021-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0091_remove_purchaseorderitem_date_updated_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
