# Generated by Django 2.2.15 on 2021-01-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0092_auto_20210113_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['product_sku', '-id']},
        ),
    ]
