# Generated by Django 2.2.15 on 2021-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0093_auto_20210114_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='outstanding_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_lines',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
