# Generated by Django 2.2.15 on 2021-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0094_auto_20210114_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='delivery_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='label',
        ),
    ]
