# Generated by Django 2.2.15 on 2021-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0095_auto_20210116_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Part Receipt', 'Part Receipt'), ('Complete', 'Complete')], max_length=200),
        ),
    ]
