# Generated by Django 2.2.15 on 2021-01-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0096_auto_20210116_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='unleashed_status',
        ),
    ]
