# Generated by Django 2.2.15 on 2021-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0098_auto_20210117_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
