# Generated by Django 2.2.15 on 2021-01-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0099_product_has_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
