# Generated by Django 2.2.15 on 2021-01-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0106_auto_20210120_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id', 'location_v2']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
