# Generated by Django 2.2.15 on 2021-01-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0107_auto_20210121_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id', 'location']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='location_v2',
            new_name='location',
        ),
    ]
