# Generated by Django 2.2.15 on 2021-01-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0109_stocksyncmagento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksyncmagento',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
