# Generated by Django 2.2.15 on 2021-01-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0110_auto_20210124_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockSyncMagento',
            new_name='MagentoProductSync',
        ),
    ]
