# Generated by Django 2.2.15 on 2021-01-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0111_auto_20210125_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='product_id',
            new_name='product',
        ),
    ]
