# Generated by Django 2.2.15 on 2021-01-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0112_auto_20210125_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magentoproductsync',
            options={'ordering': ['synced', 'id']},
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock_qty', models.IntegerField(blank=True, default=0)),
                ('new_stock_qty', models.IntegerField(blank=True, default=0)),
                ('date_checked', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.Product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
