# Generated by Django 2.2.15 on 2021-01-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0118_auto_20210129_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magentoproductsync',
            options={'ordering': ['-has_synced', '-pk']},
        ),
    ]
