# Generated by Django 2.2.15 on 2021-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0120_auto_20210129_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=200),
        ),
    ]
