# Generated by Django 2.2.15 on 2021-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0121_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_balances',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_discrepancy',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Part', max_length=200),
        ),
    ]
