# Generated by Django 2.2.15 on 2021-02-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0124_auto_20210202_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlabel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productlabel',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='productlabel',
            name='sku',
        ),
        migrations.AddField(
            model_name='productlabel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.Product'),
        ),
    ]
