# Generated by Django 2.2.15 on 2021-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0125_auto_20210202_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlabel',
            name='date_printed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
