# Generated by Django 3.0.6 on 2020-06-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0002_month_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
