# Generated by Django 3.0.6 on 2020-06-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0003_auto_20200621_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('order_qty', models.IntegerField(blank=True, default=0)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=200)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('order_qty', models.IntegerField(blank=True, default=0)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('year', models.ForeignKey(blank=True, db_column='year', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Year')),
            ],
            options={
                'ordering': ['month_id'],
            },
        ),
    ]
