# Generated by Django 3.0.6 on 2020-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0004_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day1',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('order_qty', models.IntegerField(blank=True, default=0)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
