# Generated by Django 3.0.6 on 2020-06-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0005_day1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
