# Generated by Django 3.0.6 on 2020-06-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0006_delete_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day1',
            new_name='Day',
        ),
    ]
