# Generated by Django 3.0.6 on 2020-06-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0007_auto_20200621_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='date',
            new_name='day',
        ),
    ]
