# Generated by Django 3.0.6 on 2020-06-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0009_auto_20200621_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='month',
        ),
    ]
