# Generated by Django 3.0.6 on 2020-05-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, default=0)),
                ('order_no', models.IntegerField(blank=True, default=0)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address_1', models.CharField(blank=True, max_length=200)),
                ('billing_address_2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(blank=True, max_length=200)),
                ('billing_postcode', models.CharField(blank=True, max_length=200)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('billing_email', models.CharField(blank=True, max_length=200)),
                ('billing_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('delivery_address_1', models.CharField(blank=True, max_length=200)),
                ('delivery_address_2', models.CharField(blank=True, max_length=200)),
                ('delivery_city', models.CharField(blank=True, max_length=200)),
                ('delivery_postcode', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(blank=True, max_length=200)),
                ('delivery_email', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_price', models.IntegerField(blank=True, default=0)),
                ('ip_address', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, default=0)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Product')),
            ],
            options={
                'ordering': ['entity_id'],
            },
        ),
    ]
