# Generated by Django 3.0.6 on 2020-06-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('billing_email', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(blank=True)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address_1', models.CharField(blank=True, max_length=200)),
                ('billing_address_2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(blank=True, max_length=200)),
                ('billing_postcode', models.CharField(blank=True, max_length=200)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('billing_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('delivery_address_1', models.CharField(blank=True, max_length=200)),
                ('delivery_address_2', models.CharField(blank=True, max_length=200)),
                ('delivery_city', models.CharField(blank=True, max_length=200)),
                ('delivery_postcode', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(blank=True, max_length=200)),
                ('delivery_email', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('delivery_method', models.CharField(blank=True, max_length=200)),
                ('courier', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(blank=True, max_length=3)),
                ('year', models.IntegerField(blank=True, default=0)),
                ('billing_email', models.ForeignKey(db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['supplier'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('stock_qty', models.IntegerField(blank=True, default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('brand', models.ForeignKey(blank=True, db_column='brand', default='Other', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Brand')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier', default='Unknown', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Supplier')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('ordernote_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('added_by', models.CharField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Product')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
