# Generated by Django 3.0.6 on 2020-06-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
