# Generated by Django 3.0.6 on 2020-06-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('billing_email', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
