# Generated by Django 3.0.6 on 2020-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0002_auto_20200611_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(blank=True),
        ),
    ]
