# Generated by Django 3.0.6 on 2020-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0002_auto_20200521_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='entity_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
