# Generated by Django 3.0.6 on 2020-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0002_order_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='order',
            name='address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
