# Generated by Django 3.0.6 on 2020-06-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0003_auto_20200611_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.ForeignKey(db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Customer2', to_field='billing_email'),
        ),
    ]
