# Generated by Django 3.0.6 on 2020-05-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0003_auto_20200521_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='entity_id',
            new_name='order_id',
        ),
    ]
