# Generated by Django 3.0.6 on 2020-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0004_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
