# Generated by Django 3.0.6 on 2020-05-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0004_auto_20200521_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_id']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='entity_id',
            new_name='order_id',
        ),
    ]
