# Generated by Django 3.0.6 on 2020-06-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0005_delete_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer2',
            new_name='Customer',
        ),
    ]
