# Generated by Django 3.0.6 on 2020-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0005_auto_20200521_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
