# Generated by Django 3.0.6 on 2020-05-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0006_auto_20200508_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='order_date',
        ),
    ]
