# Generated by Django 3.0.6 on 2020-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0006_orderitem_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
