# Generated by Django 3.0.6 on 2020-05-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0007_auto_20200521_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
