# Generated by Django 3.0.6 on 2020-05-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0007_auto_20200508_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
