# Generated by Django 3.0.6 on 2020-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0008_auto_20200612_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
