# Generated by Django 3.0.6 on 2020-05-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0008_auto_20200521_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
