# Generated by Django 3.0.6 on 2020-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0008_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
