# Generated by Django 3.0.6 on 2020-06-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.ForeignKey(blank=True, db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Customer', to_field='billing_email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.ForeignKey(blank=True, db_column='year', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Year'),
        ),
    ]
