# Generated by Django 3.0.6 on 2020-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_auto_20200521_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
