# Generated by Django 3.0.6 on 2020-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
