# Generated by Django 3.0.6 on 2020-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0010_auto_20200613_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month', models.IntegerField(primary_key=True, serialize=False)),
                ('month_char', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
