# Generated by Django 3.0.6 on 2020-05-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0011_auto_20200524_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Product'),
        ),
    ]
