# Generated by Django 3.0.6 on 2020-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0011_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
