# Generated by Django 3.0.6 on 2020-06-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0012_month_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(blank=True, db_column='year', default=2020, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Year'),
        ),
    ]
