# Generated by Django 3.0.6 on 2020-06-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0014_auto_20200614_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='month_year',
        ),
    ]
