# Generated by Django 3.0.6 on 2020-06-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0015_remove_month_month_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='month',
            new_name='month_id',
        ),
    ]
