# Generated by Django 3.0.6 on 2020-06-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0016_auto_20200614_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='month_char',
            new_name='month',
        ),
    ]
