# Generated by Django 3.0.6 on 2020-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0017_auto_20200524_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
