# Generated by Django 3.0.6 on 2020-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0017_auto_20200614_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
