# Generated by Django 3.0.6 on 2020-06-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0018_auto_20200614_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.ForeignKey(blank=True, db_column='month', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Month'),
        ),
    ]
