# Generated by Django 3.0.6 on 2020-05-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0018_auto_20200524_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Product'),
        ),
    ]
