# Generated by Django 3.0.6 on 2020-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0019_auto_20200614_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
