# Generated by Django 3.0.6 on 2020-05-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0020_auto_20200524_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('orderitem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True)),
                ('product_id', models.IntegerField(blank=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
