# Generated by Django 3.0.6 on 2020-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0020_product_stock_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='item_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
