# Generated by Django 3.0.6 on 2020-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0021_auto_20200616_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
