# Generated by Django 3.0.6 on 2020-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0022_product_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
