# Generated by Django 3.0.6 on 2020-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0023_ordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernote',
            name='ordernote_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
