# Generated by Django 3.0.6 on 2020-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0024_auto_20200602_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ordernote',
            name='added_by',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
