# Generated by Django 3.0.6 on 2020-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0024_auto_20200618_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='new', max_length=200),
        ),
    ]
