# Generated by Django 3.0.6 on 2020-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0025_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_order',
            field=models.CharField(blank=True, default='no', max_length=200),
        ),
    ]
