# Generated by Django 3.0.6 on 2020-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0026_auto_20200603_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernote',
            name='added_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='note',
            field=models.TextField(),
        ),
    ]
