# Generated by Django 3.0.6 on 2020-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0026_product_special_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
