# Generated by Django 3.0.6 on 2020-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0027_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='item_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='month',
            name='total_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='month',
            name='total_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='month',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='month',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
