# Generated by Django 3.0.6 on 2020-06-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0028_auto_20200620_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='item_qty',
            new_name='total_items',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_qty',
            new_name='total_orders',
        ),
    ]
