# Generated by Django 3.0.6 on 2020-06-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0028_ordernote_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
