# Generated by Django 3.0.6 on 2020-06-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0029_auto_20200620_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='total_items',
            new_name='total_item_qty',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_orders',
            new_name='total_order_qty',
        ),
    ]
