# Generated by Django 3.0.6 on 2020-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0029_auto_20200603_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(blank=True),
        ),
    ]
