# Generated by Django 3.0.6 on 2020-06-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0030_auto_20200620_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
