# Generated by Django 3.0.6 on 2020-06-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0030_auto_20200603_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_no']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order_no',
        ),
    ]
