# Generated by Django 3.0.6 on 2020-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0031_order_items_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='total_delivery',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_item_qty',
            new_name='item_qty',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_order_qty',
            new_name='order_qty',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_revenue',
            new_name='revenue',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='total_vat',
            new_name='vat',
        ),
        migrations.AddField(
            model_name='month',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
