# Generated by Django 3.0.6 on 2020-06-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0031_auto_20200603_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernote',
            name='order_id',
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order_no',
            field=models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_no',
            field=models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order'),
        ),
    ]
