# Generated by Django 3.0.6 on 2020-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0032_auto_20200620_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['month_id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='items_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
