# Generated by Django 3.0.6 on 2020-06-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0032_auto_20200603_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_id']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='order_no',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Order'),
        ),
    ]
