# Generated by Django 3.0.6 on 2020-06-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0033_auto_20200603_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.IntegerField(blank=True, default=2019),
            preserve_default=False,
        ),
    ]
