# Generated by Django 3.0.6 on 2020-06-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0033_auto_20200621_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='year',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='year',
            name='item_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='year',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
