# Generated by Django 3.0.6 on 2020-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0034_auto_20200603_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
