# Generated by Django 3.0.6 on 2020-06-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0004_month_year'),
        ('app_websites', '0034_auto_20200621_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.ForeignKey(blank=True, db_column='month', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Month'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.ForeignKey(blank=True, db_column='year', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Year'),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
