# Generated by Django 3.0.6 on 2020-06-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0008_auto_20200621_1313'),
        ('app_websites', '0035_auto_20200621_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.ForeignKey(blank=True, db_column='day', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Day'),
        ),
    ]
