# Generated by Django 3.0.6 on 2020-06-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0035_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Supplier'),
        ),
    ]
