# Generated by Django 3.0.6 on 2020-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0036_order_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stats_updates',
            field=models.BooleanField(default=False),
        ),
    ]
