# Generated by Django 3.0.6 on 2020-06-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0037_order_stats_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stats_updates',
            new_name='stats_updated',
        ),
    ]
