# Generated by Django 3.0.6 on 2020-06-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0038_auto_20200621_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stats_updated',
        ),
    ]
