# Generated by Django 3.0.6 on 2020-06-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0039_auto_20200604_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier']},
        ),
    ]
