# Generated by Django 3.0.6 on 2020-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0040_auto_20200604_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
