# Generated by Django 3.0.6 on 2020-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0040_auto_20200623_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
