# Generated by Django 3.0.6 on 2020-06-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0041_order_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-day']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
