# Generated by Django 3.0.6 on 2020-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0042_supplier_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sell_price',
        ),
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sort_order',
            field=models.IntegerField(default=100),
        ),
    ]
