# Generated by Django 3.0.6 on 2020-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0042_auto_20200623_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='day',
            new_name='date',
        ),
    ]
