# Generated by Django 3.0.6 on 2020-06-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0043_auto_20200623_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
    ]
