# Generated by Django 3.0.6 on 2020-06-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0043_auto_20200605_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('billing_email', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.ForeignKey(db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Customer'),
        ),
    ]
