# Generated by Django 3.0.6 on 2020-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0045_order_stats_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stats_updated',
            field=models.BooleanField(default=False),
        ),
    ]
