# Generated by Django 3.0.6 on 2020-06-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0045_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
