# Generated by Django 3.0.6 on 2020-06-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0009_auto_20200621_1733'),
        ('app_websites', '0046_auto_20200623_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.ForeignKey(blank=True, db_column='date', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Day'),
        ),
    ]
