# Generated by Django 3.0.6 on 2020-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0046_auto_20200606_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date']},
        ),
    ]
