# Generated by Django 3.0.6 on 2020-06-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0047_auto_20200623_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date']},
        ),
    ]
