# Generated by Django 3.0.6 on 2020-06-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0048_product_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
    ]
