# Generated by Django 3.0.6 on 2020-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0048_auto_20200624_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
