# Generated by Django 3.0.6 on 2020-06-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0049_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.OrderStatus'),
        ),
    ]
