# Generated by Django 3.0.6 on 2020-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0049_remove_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
