# Generated by Django 3.0.6 on 2020-06-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0050_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
