# Generated by Django 3.0.6 on 2020-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0051_product_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
