# Generated by Django 3.0.6 on 2020-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0052_auto_20200609_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_profit',
        ),
    ]
