# Generated by Django 3.0.6 on 2020-06-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0052_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderNote',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
