# Generated by Django 3.0.6 on 2020-06-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0053_remove_product_total_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_profit',
        ),
    ]
