# Generated by Django 3.0.6 on 2020-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0053_auto_20200626_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavTabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=200)),
                ('page', models.CharField(blank=True, max_length=200)),
                ('page_extension', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
