# Generated by Django 3.0.6 on 2020-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0054_remove_product_item_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_value',
        ),
    ]
