# Generated by Django 3.0.6 on 2020-07-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0054_navtabs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavTabs',
            new_name='NavigationTabs',
        ),
    ]
