# Generated by Django 3.0.6 on 2020-07-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0055_auto_20200702_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationTabs',
            new_name='NavigationTab',
        ),
    ]
