# Generated by Django 3.0.6 on 2020-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0055_auto_20200609_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
