# Generated by Django 3.0.6 on 2020-07-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0057_auto_20200702_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationtab',
            options={'ordering': ['page', 'sort_order']},
        ),
        migrations.CreateModel(
            name='NavigationSubTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_tab_name', models.CharField(blank=True, max_length=200)),
                ('page', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
                ('parent_tab', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.NavigationTab')),
            ],
            options={
                'ordering': ['page', 'parent_tab', 'sort_order'],
            },
        ),
    ]
