# Generated by Django 3.0.6 on 2020-07-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0059_auto_20200702_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationtab',
            options={'ordering': ['section', 'sort_order']},
        ),
        migrations.RenameField(
            model_name='navigationtab',
            old_name='page',
            new_name='section',
        ),
    ]
