# Generated by Django 3.0.6 on 2020-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0060_auto_20200703_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtab',
            name='page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
