# Generated by Django 3.0.6 on 2020-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0061_navigationtab_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationOrderTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['tab_name', 'sort_order'],
            },
        ),
    ]
