# Generated by Django 3.0.6 on 2020-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0062_navigationordertab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationordertab',
            options={'ordering': ['sort_order', 'tab_name']},
        ),
    ]
