# Generated by Django 3.0.6 on 2020-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0063_auto_20200704_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationOrderTab',
        ),
    ]
