# Generated by Django 3.0.6 on 2020-07-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0064_delete_navigationordertab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSubTab',
        ),
        migrations.DeleteModel(
            name='NavigationTab',
        ),
    ]
