# Generated by Django 3.0.6 on 2020-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0065_auto_20200704_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='part_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
