# Generated by Django 3.0.6 on 2020-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0066_auto_20200723_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_type',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
