# Generated by Django 3.0.6 on 2020-08-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0067_auto_20200727_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id', 'location']},
        ),
    ]
