# Generated by Django 3.0.6 on 2020-08-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(blank=True)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address_1', models.CharField(blank=True, max_length=200)),
                ('billing_address_2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(blank=True, max_length=200)),
                ('billing_postcode', models.CharField(blank=True, max_length=200)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('billing_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('delivery_address_1', models.CharField(blank=True, max_length=200)),
                ('delivery_address_2', models.CharField(blank=True, max_length=200)),
                ('delivery_city', models.CharField(blank=True, max_length=200)),
                ('delivery_postcode', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(blank=True, max_length=200)),
                ('delivery_email', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('items_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price_ex_vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('total_price_inc_vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('ip_address', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('status_updated', models.BooleanField(default=False)),
                ('stats_updated', models.BooleanField(default=False)),
                ('billing_email', models.ForeignKey(blank=True, db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.Customer', to_field='billing_email')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderNavTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'tab_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusType',
            fields=[
                ('status', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('icon_color', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
                ('status_type', models.ForeignKey(blank=True, db_column='status_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('orderlabel_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('delivery_address_1', models.CharField(blank=True, max_length=200)),
                ('delivery_address_2', models.CharField(blank=True, max_length=200)),
                ('delivery_city', models.CharField(blank=True, max_length=200)),
                ('delivery_postcode', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_email', models.CharField(blank=True, max_length=200)),
                ('delivery_method', models.CharField(blank=True, max_length=200)),
                ('tracking_code', models.CharField(blank=True, max_length=200)),
                ('tracking_ref', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateField(null=True)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('ordernote_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('added_by', models.CharField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('send_qty', models.IntegerField(blank=True, default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.Product')),
            ],
            options={
                'ordering': ['-order_id', '-send_qty'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, db_column='delivery_method', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderDeliveryMethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_current',
            field=models.ForeignKey(blank=True, db_column='status_current', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType'),
        ),
    ]
