# Generated by Django 3.0.6 on 2020-06-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_websites', '0053_auto_20200626_2102'),
        ('app_stats', '0012_day_month_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(blank=True)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address_1', models.CharField(blank=True, max_length=200)),
                ('billing_address_2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(blank=True, max_length=200)),
                ('billing_postcode', models.CharField(blank=True, max_length=200)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('billing_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('delivery_address_1', models.CharField(blank=True, max_length=200)),
                ('delivery_address_2', models.CharField(blank=True, max_length=200)),
                ('delivery_city', models.CharField(blank=True, max_length=200)),
                ('delivery_postcode', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(blank=True, max_length=200)),
                ('delivery_email', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=200)),
                ('delivery_method', models.CharField(blank=True, max_length=200)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('items_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price_ex_vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('total_price_inc_vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('ip_address', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('time', models.TimeField(default='00:00:00')),
                ('stats_updated', models.BooleanField(default=False)),
                ('billing_email', models.ForeignKey(blank=True, db_column='billing_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Customer', to_field='billing_email')),
                ('date', models.ForeignKey(blank=True, db_column='date', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stats.Day')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('ordernote_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('added_by', models.CharField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Product')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatus'),
        ),
    ]
