# Generated by Django 3.0.6 on 2020-06-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='desc',
            new_name='name',
        ),
    ]
