# Generated by Django 3.0.6 on 2020-08-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderNavTab',
        ),
    ]
