# Generated by Django 3.0.6 on 2020-06-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_auto_20200626_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='OrderStatusType',
        ),
    ]
