# Generated by Django 3.0.6 on 2020-06-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_auto_20200626_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
                ('status_type', models.ForeignKey(blank=True, db_column='status_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
