# Generated by Django 3.0.6 on 2020-08-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_auto_20200820_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stats_updated',
        ),
    ]
