# Generated by Django 3.0.6 on 2020-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_remove_orderstatushistory1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatushistory1',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory1',
            name='status_type',
        ),
        migrations.AddField(
            model_name='orderstatushistory1',
            name='billing_city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
