# Generated by Django 3.0.6 on 2020-06-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_auto_20200627_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory1',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order'),
        ),
    ]
