# Generated by Django 3.0.6 on 2020-06-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_orderstatushistory1_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory1',
            name='status_type',
            field=models.ForeignKey(blank=True, db_column='status_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType'),
        ),
    ]
