# Generated by Django 2.2.15 on 2020-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0008_order_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_provider_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_provider_uid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
