# Generated by Django 3.0.6 on 2020-06-27 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0009_remove_orderstatushistory1_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory1',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
