# Generated by Django 2.2.15 on 2020-09-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0009_auto_20200908_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='service_provider_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
