# Generated by Django 2.2.15 on 2020-10-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0011_order_stock_movement_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock_movement_added',
        ),
    ]
