# Generated by Django 3.0.6 on 2020-06-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0011_orderstatushistory1_status_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatushistory1',
            name='billing_city',
        ),
    ]
