# Generated by Django 3.0.6 on 2020-06-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0013_auto_20200627_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-id']},
        ),
    ]
