# Generated by Django 2.2.15 on 2020-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0014_auto_20201015_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
