# Generated by Django 3.0.6 on 2020-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0015_orderstatustype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatustype',
            name='icon_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
