# Generated by Django 2.2.15 on 2020-11-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0016_auto_20201105_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='total_price_ex_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
