# Generated by Django 3.0.6 on 2020-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0017_auto_20200628_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_updated',
            field=models.BooleanField(default=False),
        ),
    ]
