# Generated by Django 2.2.15 on 2020-11-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0017_ordershipment_total_price_ex_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='shipment_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
