# Generated by Django 3.0.6 on 2020-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0018_order_status_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='test',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
