# Generated by Django 2.2.15 on 2020-11-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0019_auto_20201106_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
    ]
