# Generated by Django 2.2.15 on 2020-11-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0020_ordershipment_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='delivery_name',
        ),
    ]
