# Generated by Django 2.2.15 on 2020-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0021_remove_ordershipment_delivery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
