# Generated by Django 3.0.6 on 2020-07-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0022_auto_20200629_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='order',
            name='status_current',
            field=models.ForeignKey(blank=True, db_column='status_current', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType'),
        ),
    ]
