# Generated by Django 2.2.15 on 2020-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0022_auto_20201110_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliverymethod',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='orderdeliverymethod',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='orderdeliverymethod',
            name='service_provider_id',
        ),
        migrations.RemoveField(
            model_name='orderdeliverymethod',
            name='service_provider_uid',
        ),
    ]
