# Generated by Django 3.0.6 on 2020-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0023_auto_20200702_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationOrderTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'tab_name'],
            },
        ),
    ]
