# Generated by Django 3.0.6 on 2020-07-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0024_navigationordertab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationOrderTab',
            new_name='OrderNavTab',
        ),
    ]
