# Generated by Django 2.2.15 on 2020-11-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0025_auto_20201110_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='service_id',
            field=models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderDeliveryMethod'),
        ),
    ]
