# Generated by Django 3.0.6 on 2020-07-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0025_auto_20200704_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
