# Generated by Django 3.0.6 on 2020-07-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0027_auto_20200705_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='updated',
            new_name='initial_updated',
        ),
    ]
