# Generated by Django 3.0.6 on 2020-07-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0028_auto_20200705_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='active',
        ),
    ]
