# Generated by Django 2.2.15 on 2020-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0029_auto_20201110_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliverymethod',
            name='service_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
