# Generated by Django 3.0.6 on 2020-07-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0029_remove_orderitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='initial_updated',
        ),
    ]
