# Generated by Django 2.2.15 on 2020-11-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0031_auto_20201110_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='delivery_method',
        ),
    ]
