# Generated by Django 3.0.6 on 2020-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0031_auto_20200727_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
