# Generated by Django 3.0.6 on 2020-07-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0032_orderdeliverymethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_method',
            new_name='delivery_method1',
        ),
    ]
