# Generated by Django 2.2.15 on 2020-11-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0033_auto_20201112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
