# Generated by Django 2.2.15 on 2020-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0034_order_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_name',
        ),
    ]
