# Generated by Django 3.0.6 on 2020-07-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0034_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method1',
        ),
    ]
