# Generated by Django 3.0.6 on 2020-07-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0035_remove_order_delivery_method1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, db_column='delivery_method', default=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderDeliveryMethod'),
        ),
    ]
