# Generated by Django 2.2.15 on 2020-11-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0035_auto_20201115_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
