# Generated by Django 3.0.6 on 2020-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0036_auto_20200730_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='send_qty_init_updated',
            field=models.BooleanField(default=False),
        ),
    ]
