# Generated by Django 2.2.15 on 2020-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0036_order_delivery_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_country_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
