# Generated by Django 3.0.6 on 2020-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0037_orderitem_send_qty_init_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdeliverymethod',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdeliverymethod',
            name='sort_order',
            field=models.IntegerField(default=100),
        ),
    ]
