# Generated by Django 2.2.15 on 2020-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0037_ordershipment_delivery_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_created', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Recevied'), ('Shipement Created', 'Shipment Created'), ('Order Delivered', 'Order Delivered')], max_length=200),
        ),
    ]
