# Generated by Django 2.2.15 on 2020-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0038_auto_20201127_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Recevied'), ('Shipement Created', 'Shipment Created'), ('Order Delivered', 'Order Delivered')], default='Order Received', max_length=200),
        ),
    ]
