# Generated by Django 3.0.6 on 2020-07-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0038_auto_20200730_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['orderitem_id', '-send_qty']},
        ),
    ]
