# Generated by Django 2.2.15 on 2020-11-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0040_auto_20201127_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_current',
            field=models.ForeignKey(blank=True, db_column='status_current', default='10', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType'),
        ),
    ]
