# Generated by Django 3.0.6 on 2020-08-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0041_auto_20200801_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('orderlabel_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(blank=True, max_length=200)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
            ],
        ),
    ]
