# Generated by Django 2.2.15 on 2020-11-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0041_auto_20201127_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_current',
            field=models.ForeignKey(blank=True, db_column='status_current', default='60', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderStatusType'),
        ),
    ]
