# Generated by Django 3.0.6 on 2020-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0042_ordershipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
