# Generated by Django 3.0.6 on 2020-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0043_auto_20200803_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
