# Generated by Django 2.2.15 on 2020-11-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0043_order_return_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_updated',
            new_name='initial_status_added',
        ),
    ]
