# Generated by Django 3.0.6 on 2020-08-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0044_ordershipment_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='tracking_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
