# Generated by Django 2.2.15 on 2020-11-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0044_auto_20201127_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_orders.Order')),
                ('inspection_passed', models.BooleanField(default=False)),
                ('inspection_passed_date', models.DateTimeField()),
            ],
        ),
    ]
