# Generated by Django 2.2.15 on 2020-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0045_orderreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inspection_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='inspection_passed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item_received_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item_refunded_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='OrderReturn',
        ),
    ]
