# Generated by Django 3.0.6 on 2020-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0046_ordershipment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='date_delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='date_despatched',
            field=models.DateTimeField(null=True),
        ),
    ]
