# Generated by Django 3.0.6 on 2020-08-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0047_auto_20200804_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipment',
            old_name='date_despatched',
            new_name='date_sent',
        ),
    ]
