# Generated by Django 3.0.6 on 2020-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0049_auto_20200804_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_date',
            field=models.DateField(null=True),
        ),
    ]
