# Generated by Django 3.0.6 on 2020-08-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0050_order_send_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='send_date',
            new_name='date_sent',
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='date_sent',
            field=models.DateField(null=True),
        ),
    ]
