# Generated by Django 2.2.15 on 2020-12-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0051_refundorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefundOrder',
            new_name='RefundOrder2',
        ),
    ]
