# Generated by Django 3.0.6 on 2020-08-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0051_auto_20200806_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, db_column='delivery_method', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderDeliveryMethod'),
        ),
    ]
