# Generated by Django 2.2.15 on 2020-12-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0052_auto_20201202_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundOrder2',
        ),
    ]
