# Generated by Django 3.0.6 on 2020-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0052_auto_20200806_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
