# Generated by Django 2.2.15 on 2020-12-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0055_auto_20201202_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(blank=True, max_length=200)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('item_qty', models.IntegerField(blank=True, default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('stock_movement_added', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order')),
                ('orderitem_id', models.OneToOneField(blank=True, db_column='orderitem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderItem')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
