# Generated by Django 2.2.15 on 2020-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0056_refundorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorderitem',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('Order Item Refund', 'Order Item Refund'), ('Postage Refund', 'Postage Refund'), ('Other Refund', 'Other Refund')], max_length=200),
        ),
    ]
