# Generated by Django 2.2.15 on 2020-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0057_auto_20201203_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='refund_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
