# Generated by Django 2.2.15 on 2020-12-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0059_auto_20201203_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorderitem',
            name='order_id',
        ),
        migrations.AddField(
            model_name='refundorderitem',
            name='refundorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.RefundOrder'),
        ),
    ]
