# Generated by Django 2.2.15 on 2020-12-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0060_auto_20201204_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.Order'),
        ),
    ]
