# Generated by Django 2.2.15 on 2020-12-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0061_refundorderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='refund_note',
            new_name='line_description',
        ),
    ]
