# Generated by Django 2.2.15 on 2020-12-04 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0066_auto_20201204_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
