# Generated by Django 2.2.15 on 2020-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0067_refundorderitem_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refunded_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
