# Generated by Django 2.2.15 on 2020-12-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0068_orderitem_refunded_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sagepay_tx_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
