# Generated by Django 2.2.15 on 2020-12-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0069_order_sagepay_tx_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorder',
            name='auth_code',
        ),
    ]
