# Generated by Django 2.2.15 on 2020-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0070_remove_refundorder_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='xero_line_items',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
