# Generated by Django 2.2.15 on 2020-12-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0071_refundorderitem_xero_line_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='xero_line_items',
            new_name='xero_line_item',
        ),
    ]
