# Generated by Django 2.2.15 on 2020-12-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0074_auto_20201215_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='orderitem_id',
            field=models.ForeignKey(blank=True, db_column='orderitem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_orders.OrderItem'),
        ),
    ]
