# Generated by Django 2.2.15 on 2020-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0075_refundorderitem_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorderitem',
            name='orderitem_id',
        ),
    ]
