# Generated by Django 2.2.15 on 2020-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0076_remove_refundorderitem_orderitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='orderitem_id_2',
            new_name='orderitem_id',
        ),
    ]
