# Generated by Django 2.2.15 on 2020-12-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0078_order_sagepay_tx_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
    ]
