# Generated by Django 2.2.15 on 2021-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0079_auto_20201224_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sagepay_tx_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sagepay_tx_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
