# Generated by Django 2.2.15 on 2021-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0083_order_delivery_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_tax_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
