# Generated by Django 2.2.15 on 2020-11-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('printnode_id', models.PositiveIntegerField(blank=True, default=0)),
                ('computer_control', models.CharField(blank=True, choices=[('Ben Laptop', 'Ben Laptop'), ('Label Desktop', 'Label Desktop'), ('Jodie Desktop', 'Jodie Desktop'), ('Nick Desktop', 'Nick Desktop'), ('Warehouse Desktop', 'Warehouse Desktop')], max_length=200, null=True)),
            ],
            options={
                'ordering': ['printer_name'],
            },
        ),
    ]
