# Generated by Django 2.2.15 on 2020-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='computer_control',
            field=models.CharField(blank=True, choices=[('Ben Laptop - 331090', 'Ben Laptop'), ('Label Desktop', 'Label Desktop'), ('Jodie Desktop', 'Jodie Desktop'), ('Nick Desktop', 'Nick Desktop'), ('Warehouse Desktop', 'Warehouse Desktop')], max_length=200, null=True),
        ),
    ]
