# Generated by Django 2.2.15 on 2020-11-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0002_auto_20201120_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='computer_control',
            field=models.CharField(blank=True, choices=[('Ben Laptop - 331090', 'Ben Laptop'), ('Label Desktop - 265194', 'Label Desktop'), ('Jodie Desktop - 318172', 'Jodie Desktop'), ('Nick Desktop', 'Nick Desktop'), ('Warehouse Desktop - 332120', 'Warehouse Desktop')], max_length=200, null=True),
        ),
    ]
