# Generated by Django 2.2.15 on 2020-11-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0004_printprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintProcess',
        ),
    ]
