# Generated by Django 2.2.15 on 2020-11-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0006_printprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printprocess',
            name='process_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
