# Generated by Django 2.2.15 on 2020-11-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0007_auto_20201120_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['computer_control', 'printer_name']},
        ),
    ]
