# Generated by Django 2.2.15 on 2021-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0008_auto_20201122_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
