# Generated by Django 2.2.15 on 2021-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0009_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='api',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
