# Generated by Django 2.2.15 on 2021-01-12 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0010_apilog_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='api',
            new_name='api_service',
        ),
        migrations.AddField(
            model_name='apilog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
