# Generated by Django 2.2.15 on 2021-01-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0011_auto_20210112_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apiLog',
        ),
    ]
