# Generated by Django 2.2.15 on 2021-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0012_delete_apilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_service', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.CharField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
