# Generated by Django 2.2.15 on 2021-01-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0014_apilog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='status',
        ),
    ]
