# Generated by Django 2.2.15 on 2021-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0016_auto_20210112_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='response',
            new_name='response_text',
        ),
        migrations.AddField(
            model_name='apilog',
            name='response_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
