# Generated by Django 2.2.15 on 2021-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0017_auto_20210112_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='api_service',
            field=models.CharField(blank=True, choices=[('Magento', 'Magento'), ('Ship Theory', 'Ship Theory'), ('Mailgun', 'Mailgun'), ('Xero', 'Xero'), ('Sagepay', 'Sagepay')], max_length=200, null=True),
        ),
    ]
