# Generated by Django 2.2.15 on 2021-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0018_auto_20210129_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='api_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
